version: '3.8'

networks:
  rede_microsservicos:
    external: true

services:
  mysql:
    build: .
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estacoes_parametros_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.5

  controller-gerenciamento-estacoes-metricas:
    image: jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:develop
    ports:
      - "3001:3001"
    restart: always
    networks:
      rede_microsservicos:
        ipv4_address: 172.18.0.6
    depends_on:
      - mysql

  typeorm-migration:
    build: .
    depends_on:
      - mysql
    command: npm run typeorm -- -d ./src/database/data-source.ts migration:run
    networks:
      - rede_microsservicos

volumes:
  mysql-data:
