name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start job
        run: echo "Starting job"

  build_and_deploy:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build and tag Docker image
        run: |
          docker build -t jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas .
          docker tag jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:latest jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:prod
          docker tag jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:latest jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:develop

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u jonasrsribeiro --password-stdin

      - name: Push Docker image to Docker Hub
        run: |
          docker push jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:latest
          docker push jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:prod
          docker push jonasrsribeiro/lw-controller-gerenciamento-estacoes-metricas:develop
          

      - name: Merge to prod (somente quando executado na branch develop)
        if: success() && github.ref == 'refs/heads/develop'
        env:
          GHUB_TOKEN: ${{ secrets.GHUB_TOKEN }}
        run: |
          git config user.name "jonasrsribeiro"
          git config user.email "jonas.ribeiro01@fatec.sp.gov.br"
          git fetch origin  # Certifique-se de buscar as atualizações mais recentes
          git checkout develop
          git pull origin develop
          git checkout prod
          git merge --allow-unrelated-histories --strategy-option=theirs develop  # Merge forçado escolhendo automaticamente as alterações da branch develop
          git push origin prod  # Para enviar o merge para a branch prod no repositório remoto

      - name: Some action (somente quando executado na branch prod)
        if: success() && github.ref == 'refs/heads/prod'
        run: |
          # Coloque aqui os comandos que você deseja executar
